# 숫자야구게임
# 컴퓨터가 랜덤으로 1~9 사이의 임의의 숫자를 3개 생성
# 사용자로부터 1~9 사이의 중복없는 3자리 숫자를 입력받기
# 456 == 임의의 숫자를 3개와 비교 => 3개의 숫자를 다 맞췄다면 3스트라이크
# 2개만 맞췄다면 0스트라이크 2볼
# q를 입력하기 전까지는 계속 반복
# 3스트라이크가 나온다면 반복문 중단

import random
import time
import oracledb

'''내가 짠거
def make_answer():
    """1~9중 중복없는 3자리 숫자 생성"""
    answer2 = []
    while(len(answer2)!=3):
        answer = random.randrange(9) +1
        # print(answer)
        if(len(answer2)==1):
            if(answer2[0] == answer):
                continue
            else:
                answer2.append(answer)
        elif(len(answer2)==2):
            if(answer2[0] == answer):
                continue
            elif(answer2[1] == answer):
                continue
            else:
                answer2.append(answer)
        else:
            answer2.append(answer) 

    return answer2

def get_strike_ball(answer, guess):
    """답변 하고 응답하고 비교 후 strike, ball 값 리턴"""
    st = 0
    ball = 0
    for i in range(3):
        for j in range(3):
            # print(f'{answer[j]}({j}) : {guess[i]}({i})')
            if(i==j and answer[j] == guess[i]):
                st += 1
                # print(st)
            elif(i!=j and answer[j] == guess[i]):
                ball += 1
                # print(ball)

    print(f'{st} : 스트라이크\n{ball} : 볼')
    if(st == 3):
        return 0
    else:
        return 1

    

# print(answer)
i = 1
attempts = 0

answer = make_answer()
while(i):
    guess = []
    for k in range(3):
        dum = int(input(f'정답을 입력하세요{k+1}'))
        guess.append(dum)
    i = get_strike_ball(answer,guess)
    attempts +=1

print(f'시도횟수 : {attempts}')
'''


def make_answer2():
    return random.sample(range(1,10), k=3)

def get_strike_ball2(answer, guess):
    strike,ball = 0,0

    for i in range(3):
        if(guess[i]==answer[i]):
            strike += 1
        elif(guess[i]in answer):
            ball += 1
    return strike,ball
        

# 정답(숫자 3개) 리스트 생성
answer = make_answer2()
# 시도횟수
attempts = 0
# 프로그램 중단 여부
is_quit = False

print("=== 숫자 야구 게임 ===")
print("1~9 사이 중복 없는 3자리 숫자를 맞춰 보세요.")

start = time.time()
while True:
    # 사용자로부터 숫자 3개 입력받기
    guess_input = input("숫자 3개를 입력하세요 (예:123): ").strip()

    if(guess_input.lower() == 'q'):
        print('게임을 종료합니다.')
        is_quit = True
        break

    # 3자리 맞는지 확인, 숫자가 맞는지 확인
    if len(guess_input) != 3 or not guess_input.isdigit():
        print("3자리 숫자로 입력해 주세요.")
        continue

    # answer [1,3,5]
    # 입력값 "123" => [1,2,3]
    # guess = []
    # for ch in guess_input:
    #     guess.append(int(ch))
    guess = [int(ch) for ch in guess_input]
    attempts += 1

    strike, ball = get_strike_ball2(answer, guess)

    if strike == 3:
        print(f"정답입니다!! {strike}")
        break
    else : 
        print(f'{strike}스트라이크 {ball}볼')

end = time.time()
# 걸린시간
elapsed = format(end - start, ".3f")

# 중간에 종료 해싿면 기록을 남기지 말고 프로그램 종료
if is_quit:
    exit()

print(f'시도 횟수 {attempts}회, 걸린시간 : {elapsed}초')

# 오라클 연동
# baseball_records 테이블생성
# record_id 자동증가,게임일자,걸린시간,시도횟수

with oracledb.connect(user = 'python_user', password = '2394', dsn = 'localhost/xe')as conn:
    with conn.cursor() as cursor:
        # record_id : 자동증가 컬럼

        try:

            sql = """create table baseball_records(
            record_id   number(10)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            attempts number,
            elapsed varchar2(20),
            regdate date 
            )
            """

            cursor.execute(sql)
        except oracledb.DatabaseError as e:
            (error_obj,) = e.args
            if error_obj.code == 955:
                print(error_obj.message)
            else:
                raise


        # insert 작업(기록 삽입)
        from datetime import datetime
        now = datetime.now()
        nowDateTime = now.strftime("%Y-%m-%d %H:%M:%S")
        sql = "insert into baseball_records(attempts,elapsed,regdate) values(:1,:2,sysdate)"
        cursor.execute(sql, (attempts, elapsed))
        conn.commit()

print('기록이 저장 되었습니다.')