# === Todo 관리 ====
# 1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료
# 선택 : 1
# 할 일 내용을 입력하세요: 내용입력...
# 등록되었습니다.
# === Todo 관리 ====
# 1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료
# 선택 : 2
# ----------------------------------
# 1. [미완료] 강아지 목욕(2026-08-20 12:38:07)
# === Todo 관리 ====
# 1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료
# 선택 : 3
# 완료 처리할 일 번호를 입력하세요: 1
# 완료 처리되었습니다.
# === Todo 관리 ====
# 1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료
# 선택 : 4
# 삭제 처리할 일 번호를 입력하세요: 1
# 삭제 처리되었습니다.


# 데이터베이스 테이블 구조
# todo_id 자동증가,pk
# title not null
# is_done number(1) default 0
# created_at 작성일자 sysdate
import oracledb

conn = oracledb.connect(user='python_user', password='2394', dsn='localhost/xe')
cursor = conn.cursor()

# 테이블 생성
try:
    sql = """
    CREATE TABLE todos (
        todo_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title       VARCHAR2(200) NOT NULL,
        is_done     NUMBER(1) DEFAULT 0,
        created_at  DATE DEFAULT SYSDATE
    )
    """
    cursor.execute(sql)
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955:
        pass
    else:
        raise


def add_todo():
    '''create'''
    title = input('할 일 내용을 입력하세요 : ').strip()
    if not title:
        print('내용을 입력해주세요.\n')
        return

    sql = 'INSERT INTO todos (title, created_at) VALUES (:1, SYSDATE)'
    cursor.execute(sql, (title,))
    conn.commit()
    print('등록되었습니다.\n')


def list_todos():
    '''select'''
    sql = 'SELECT todo_id, title, is_done, TO_CHAR(created_at, \'YYYY-MM-DD HH24:MI:SS\') FROM todos ORDER BY todo_id'
    cursor.execute(sql)
    rows = cursor.fetchall()

    if not rows:
        print('등록된 할일 목록은 없습니다.\n')
        return

    print('-' * 50)
    for row in rows:
        # row[2]는 is_done 값 (1: 완료, 0: 미완료)
        status = '완료' if row[2] == 1 else '미완료'
        print(f'{row[0]}. [{status}] {row[1]} ({row[3]})')
    print('-' * 50)
    print()


def update_todo():
    '''완료처리 - update'''
    list_todos()
    todo_id = input('완료 처리할 일 번호를 입력하세요: ').strip()
    sql = 'UPDATE todos SET is_done = 1 WHERE todo_id = :1'
    # 튜플 형태로 전달 (todo_id,)
    cursor.execute(sql, (todo_id,))
    conn.commit()

    if cursor.rowcount == 0:
        print("해당 번호가 없습니다.\n")
    else:
        print('완료 처리 되었습니다.\n')


def delete_todo():
    '''삭제처리 - delete'''
    list_todos()
    todo_id = input("삭제 처리할 일 번호를 입력하세요: ").strip()
    sql = "DELETE FROM todos WHERE todo_id = :1"
    cursor.execute(sql, (todo_id,))
    conn.commit()

    if cursor.rowcount == 0:
        print("해당 번호가 없습니다.\n")
    else:
        print("삭제 처리되었습니다.\n")


def menu():
    while True:
        print("=== Todo 관리 ===")
        print("1. 추가 2. 목록 3. 완료처리 4. 삭제 5. 종료")

        choice = input("선택 : ").strip()

        if choice == "1":
            add_todo()
        elif choice == "2":
            list_todos()
        elif choice == "3":
            update_todo()
        elif choice == "4":
            delete_todo()
        elif choice == "5":
            print("종료합니다.")
            break
        else:
            print("번호를 확인해 주세요.\n")


if __name__ == '__main__':
    try:
        menu()
    finally:
        cursor.close()
        conn.close()