import random
import time
import oracledb

conn = oracledb.connect(user='python_user', password='2394', dsn='localhost/xe')
cursor = conn.cursor()

sentences = [
    "The quick brown fox jumps over the lazy dog",
    "Python is a powerful programming language",
    "Practice makes perfect every single day",
    "Oracle database stores data reliably",
    "Typing speed improves with daily practice"
]

# 1. 테이블 생성 (없으면 생성)
try:
    sql_create = """
    CREATE TABLE typing_records (
        record_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        elapsed_sec NUMBER(6, 2) NOT NULL,
        accuracy    NUMBER(5, 2) NOT NULL
    )
    """
    cursor.execute(sql_create)
except oracledb.DatabaseError as e:
    (error_obj,) = e.args
    if error_obj.code == 955:  # 이미 테이블이 존재하는 경우
        pass
    else:
        raise

# 2. 타자 연습 실행 함수 예시
def run_typing_game():
    # 임의의 문장 1개 선택
    target = random.choice(sentences)
    print("\n[다음 문장을 그대로 입력하세요]")
    print(f"제시문: {target}")
    
    start_time = time.time()
    user_input = input("입력  : ").strip()
    end_time = time.time()
    
    # 걸린 시간 계산
    elapsed = round(end_time - start_time, 2)
    
    # 정확도 계산 (글자 단위 일치율)
    correct_chars = sum(1 for a, b in zip(target, user_input) if a == b)
    accuracy = round((correct_chars / max(len(target), len(user_input))) * 100, 2)
    
    print(f"\n걸린 시간: {elapsed}초 | 정확도: {accuracy}%")
    
    # DB 저장
    sql_insert = "INSERT INTO typing_records (elapsed_sec, accuracy) VALUES (:1, :2)"
    cursor.execute(sql_insert, (elapsed, accuracy))
    conn.commit()
    print("기록이 저장되었습니다.\n")


if __name__ == '__main__':
    try:
        run_typing_game()
    finally:
        cursor.close()
        conn.close()

# sentences 문장 중 임의의 문장을 출제후 사용자가 타이핑하는 시간을 잰 후 저장
# 정확도 계산

# 걸린시간, 정확도율, 날짜
