[project]
name = "fastapi-source"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "leetaeyong", email = "tkwk651@naver.com" }
]
requires-python = ">=3.9"
dependencies = [
    "alembic>=1.16.5",
    "fastapi[standard]>=0.128.8",
    "oracledb>=4.0.2",
    "pwdlib[argon2]>=0.2.1",
    "pyjwt>=2.15.1",
    "sqlalchemy==2.0.54",
]

[project.scripts]
fastapi-source = "fastapi_source:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
