# 영어타자 프로그램

# word.txt 읽어서
# 섞는다 random.shuffle()
# 임의로 하나 추출 random.choice()

# Q1) then
# input()
# input 결과에 딸 정답!! or 오타!!

# 문제 5문제 출제
# 정답 개수

# 게임시간 출력
# 출력문 => 게임시간 : 10초, 정답개수 : 3개
# 3개이상 정답인 경우 합격 or 불합격

import time, random
import oracledb
from dotenv import load_dotenv 
import os

password =  os.getenv('oracle_password')

game_count = 0

word_txt=[]

with open ('./data/word.txt','r',encoding='utf-8') as f:

    list1 = f.readlines()
    random.shuffle(list1)
    for i in range(5):
        choice1 = random.choice(list1).strip()
        word_txt.append(choice1)

    #print(word_txt)

start = time.time()
for i in word_txt:
    print(i)
    ok = input('입력하라')

    if(i == ok):
        print('정답')
        game_count += 1
    else:
        print('틀림')

if game_count >= 3:
    print('합격')
else:
    print('나가')

end = time.time()
et = time.time()- start
print(f'총 정답 : {game_count}\n시간 : {(et):.2f}')




# db
import sqlite3
# conn = sqlite3.connect("../db/test.db", isolation_level=None)
# cursor = conn.cursor()

with oracledb.connect(user = 'python_user', password = '2394', dsn = 'localhost/xe')as conn:
    with conn.cursor() as cursor:
        # record_id : 자동증가 컬럼

        try:

            sql = """create table records(
            record_id   number(10)  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            corr_cnt number,
            record varchar2(20),
            regdate varchar2(30)
            )
            """

            cursor.execute(sql)
        except oracledb.DatabaseError as e:
            (error_obj,) = e.args
            if error_obj.code == 955:
                print(error_obj.message)
            else:
                raise

        # insert 작업(기록 삽입)
        from datetime import datetime
        now = datetime.now()
        nowDateTime = now.strftime("%Y-%m-%d %H:%M:%S")
        sql = "insert into records(corr_cnt,record,regdate) values(:1,:2,:3)"
        cursor.execute(sql, (game_count, et, nowDateTime))
        conn.commit()

print('기록이 저장 되었습니다.')






